/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoParking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Rafael
 */
public class PanelListarVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form PanelListarVehiculos
     */
    public PanelListarVehiculos() {
        initComponents();
        
        rbFueraParq.setSelected(true);
        TableColumnModel columnModel = tblVehiculos.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(1).setPreferredWidth(70);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(70);
        columnModel.getColumn(5).setPreferredWidth(70);
        columnModel.getColumn(5).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoB2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        tfPropietario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbAuto = new javax.swing.JCheckBox();
        cbMoto = new javax.swing.JCheckBox();
        rbEnParq = new javax.swing.JRadioButton();
        rbFueraParq = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        dcFechaBusqueda = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(223, 238, 232));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(689, 429));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Vehiculos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Placa");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Propietario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Fecha");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        tfPlaca.setBackground(new java.awt.Color(255, 255, 255));
        add(tfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 112, 38));

        tfPropietario.setBackground(new java.awt.Color(255, 255, 255));
        add(tfPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 141, 38));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de vehiculo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Ubicacion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        cbAuto.setBackground(new java.awt.Color(255, 255, 255));
        cbAuto.setText("Automovil");
        cbAuto.setContentAreaFilled(false);
        cbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAutoActionPerformed(evt);
            }
        });
        add(cbAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        cbMoto.setBackground(new java.awt.Color(255, 255, 255));
        cbMoto.setText("Motocicleta");
        cbMoto.setContentAreaFilled(false);
        add(cbMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        rbEnParq.setBackground(new java.awt.Color(255, 255, 255));
        GrupoB2.add(rbEnParq);
        rbEnParq.setText("Estacionamiento");
        rbEnParq.setContentAreaFilled(false);
        rbEnParq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnParqActionPerformed(evt);
            }
        });
        add(rbEnParq, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        rbFueraParq.setBackground(new java.awt.Color(255, 255, 255));
        GrupoB2.add(rbFueraParq);
        rbFueraParq.setText("Fuera");
        rbFueraParq.setContentAreaFilled(false);
        add(rbFueraParq, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        tblVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Placa", "Propietario", "Tipo de vehiculo", "Hora de entrada", "Hora de salida", "Pago"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 630, 120));

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 102, 204));
        button1.setLabel("Buscar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 129, 39));

        button2.setBackground(new java.awt.Color(255, 255, 255));
        button2.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        button2.setForeground(new java.awt.Color(0, 102, 204));
        button2.setLabel("Cierre");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 129, 39));
        add(dcFechaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rbEnParqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnParqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEnParqActionPerformed

    String consulta;
    String tipoVehiculo = "otro", estado = "", fecha = "";
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
         DefaultTableModel modelo = (DefaultTableModel) tblVehiculos.getModel();
        modelo.setRowCount(0);

        if (cbAuto.isSelected()) {
            if (cbMoto.isSelected()) {
                tipoVehiculo = "";
            } else {
                tipoVehiculo = "Automovil";
            }
        } else if (cbMoto.isSelected()) {
            tipoVehiculo = "Motocicleta";
        }

        if (rbFueraParq.isSelected()) {
            estado = "No Disponible";
        }
        if (rbEnParq.isSelected()) {
            estado = "Disponible";
        }
        if (dcFechaBusqueda.getDate() != null) {
            DateFormat dateFormat = new SimpleDateFormat("0");
            Date date = dcFechaBusqueda.getDate();
            fecha = dateFormat.format(date);
        }

        try {
            // TODO add your handling code here:

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/estacionamiento", "root", "");
            Statement stat = con.createStatement();
            consulta = "SELECT * FROM vehiculos WHERE Estado='" + estado + "' AND TipoVehiculo LIKE'%" + tipoVehiculo + "%' AND Placa LIKE '%" + tfPlaca.getText() + "%' AND Propietario LIKE '%" + tfPropietario.getText() + "%' AND HoraEntrada LIKE '" + fecha + "%'";
            System.out.println(consulta);
            ResultSet rs = stat.executeQuery(consulta);
            rs.first();

            do {
                String horasalida = rs.getString(6);
                String pago = rs.getString(7);
                if (horasalida == null) {
                    horasalida = "No ha salido";
                    pago = "0";
                } else {
                    horasalida = rs.getString(6).substring(10).substring(0,6);
                    pago = rs.getString(7);
                }
                String[] fila = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5).substring(10).substring(0, 6), horasalida, "$" + pago};
                modelo.addRow(fila);
            } while (rs.next());

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelListarVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelListarVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/estacionamiento", "root", "");
            Statement stat = con.createStatement();
            consulta = "SELECT SUM(valorpagado)FROM vehiculos WHERE Estado='" + estado + "' AND TipoVehiculo LIKE'%" + tipoVehiculo + "%' AND Placa LIKE '%" + tfPlaca.getText() + "%' AND Propietario LIKE '%" + tfPropietario.getText() + "%' AND HoraSalida LIKE '" + fecha + "%'";
            ResultSet rs = stat.executeQuery(consulta);
            rs.first();
            DecimalFormat df = new DecimalFormat("#.00");
            Double IngresosTotales = Double.parseDouble(rs.getString(1));
            JOptionPane.showMessageDialog(null, "El ingreso total del dia seleccionado es de : $ " + df.format(IngresosTotales) + " Pesos");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelListarVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelListarVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void cbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoB2;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JCheckBox cbAuto;
    private javax.swing.JCheckBox cbMoto;
    private com.toedter.calendar.JDateChooser dcFechaBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbEnParq;
    private javax.swing.JRadioButton rbFueraParq;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfPropietario;
    // End of variables declaration//GEN-END:variables
}
